### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by rosostolato** [AlisonQueiroz/curriculum-master#1]
Já está habilitado no github pages? Tentei acessar em https://alisonqueiroz.github.io/curriculum-master/ e não foi.

**Comment by AlisonQueiroz** [comment]
Coloquei online via firebase: https://alison-curriculo.web.app/

**Comment by AlisonQueiroz** [comment]
Mas vou abrir aqui também, valeu!

**Comment by rosostolato** [comment]
Ahh sim, acho que no firebase já tá top!

**Comment by rosostolato** [comment]
Coloca esse link na descrição do repositorio aqui no github

**Comment by AlisonQueiroz** [comment]
boa, vou colocar!

**Comment by rosostolato** [comment]
Eu conheço esse template aí heim kkk

**Comment by AlisonQueiroz** [comment]
hahahaha po, impressão sua, esse é totalmente original

**Comment by rosostolato** [comment]
O tic tac toe ta funcionando no multiplayer?

**Comment by AlisonQueiroz** [comment]
ta sim

**Comment by AlisonQueiroz** [comment]
tem um bugzinho na hora de reiniciar o game, mas o resto ta ok

**Comment by rosostolato** [comment]
não consegui fazer o login com google nao

**Comment by rosostolato** [comment]
![image](https://user-images.githubusercontent.com/27731641/116617641-760dfb80-a914-11eb-9f17-057753b03d60.png)

**Comment by AlisonQueiroz** [comment]
vish, vou dar uma olhada

**Comment by rosostolato** [comment]
não ta chegando o email pra confirmar

**Comment by rosostolato** [comment]
eu criei uma sala como guest, entra aí
dW7jzhufaGw5DO3jiUy9

**Comment by AlisonQueiroz** [comment]
Entrei

**Comment by rosostolato** [comment]
Top!! Faltou o placar, chat kkk

**Comment by AlisonQueiroz** [comment]
Sim kkkk, ainda vou fazer, mas ficou maneiro ne?

**Comment by rosostolato** [comment]
Muito bom, parabéns! Já que vc ta usando esse projeto como portifólio, tenta trabalhar no design dele, tirar essa cara de material. Acho que seria uma boa!

**Comment by rosostolato** [comment]
Seria bacana se vc usasse web message pra gerar notificação... é legal pra aprender

**Comment by AlisonQueiroz** [comment]
Pode crer, preciso melhorar essas coisas... Valeu mano!

**Comment by rosostolato** [comment]
Nada, joga lá a última partida kkk

**Comment by rosostolato** [comment]
kkkkk... muito bom! vou sair aqui

**Comment by AlisonQueiroz** [comment]
kkkk taí, 1x1

**Comment by rosostolato** [comment]
ahh quer desempatar?

**Comment by AlisonQueiroz** [comment]
bora

**Comment by rosostolato** [comment]
blz

**Comment by AlisonQueiroz** [comment]
acho q nunca vai desempatar kkk

**Comment by AlisonQueiroz** [comment]
aee

**Comment by rosostolato** [comment]
pronto kkk desempatou kkk

**Comment by rosostolato** [comment]
depois me mostra o código

**Comment by AlisonQueiroz** [comment]
Show!
